name: Copyright Header Check

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - '**'  # Matches all branches
  workflow_dispatch:

jobs:
  copyright-check:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Run copyright header check
      run: |
        python -m pytest -v tests/others/test_copyright.py